USE HowKteam
GO

SELECT MAGV FROM dbo.GIAOVIEN
WHERE LUONG >= 2500
UNION
SELECT MAGV FROM dbo.GIAOVIEN
WHERE  PHAI = N'Nữ'

SELECT dbo.GIAOVIEN.MAGV FROM dbo.GIAOVIEN JOIN dbo.NGUOITHAN
ON LUONG >= 2500 AND NGUOITHAN.PHAI = N'Nữ'